# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: gdsc-web-backend-bucket
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
      env:
        CI: ""
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Create Spring Properties
      run: |
          touch src/main/resources/application-dev.properties
          echo "$DEV_SPRING_PROPERTIES" > application-dev.properties.b64
          base64 -d -i application-dev.properties.b64 > src/main/resources/application-dev.properties
      env:
          DEV_SPRING_PROPERTIES: ${{ secrets.DEV_SPRING_PROPERTIES }}

    - name: Build with Gradle
      run: ./gradlew clean build -Pprofile=dev


      #work flow 시간
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

 
